language: ruby
bundler_args: --binstubs --without development
node:
- 8.9.0
addons:
  ssh_known_hosts: blog.pagansoft.de
before_install:
- npm install -g amphtml-validator
before_script:
- sudo apt-get install -qq sshpass
script: rake travis
branches:
  only:
  - master
env:
  global:
  - secure: jQcioeKO6pYIQp+10FKrMIFYauAYptDJ9vClBFACDiT7W/6zjYLrnMtJLGAoMbewUuzktR7YqkWkj8+8J/4ZickQr1BtaVqaC++WEgGPhM1dTXg7L2BJVQs+yAo19bpzdH9pQ+NvaQhbNXa3wF93PlY9mwu8EGni/bwi3R9Hngg=
  - secure: oCKYFI+cIOeenaShLSM0G1Db5k9rMUy8uBmCAAZu1Yo0c6L/K5UVH/ThGNSvBrU8qOrzg6w4iGQCiHqt/ZgreMqAWm5tQGEiUojLgYAmP10ctg1hc5HFqPalJBt/7h8vewiCdF5XdcfREuQDgdbCBBtuzKd0E2YDXR/6XOUJXE8=
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
