source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-compass'
gem 'jekyll-paginate'
gem 'jekyll-tagging'
gem 'jekyll-twitter-plugin'
gem 'sass'
gem 'kramdown'
gem 'pygments.rb'
gem 'jekyll-youtube'
gem 'nokogiri'
gem 'html-proofer'
gem 'rake'
gem 'dotyaml'
